#! /usr/bin/env node

/*************************************************************************
 *
 *  puppeteer/typeset
 *
 *  Uses MathJax v4 to convert a any input format to any output format
 *  inside a headless Chrome via puppeteer.
 *
 * ----------------------------------------------------------------------
 *
 *  Copyright (c) 2020-2025 The MathJax Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

//
// Load the needed utilities.
//
import {Typeset} from '../mjs/util/Typeset.js';
import {Util} from '../mjs/util/Util.js';
import {Tex} from '../mjs/util/Tex.js';
import {Mml} from '../mjs/util/Mml.js';
import {Am} from '../mjs/util/Am.js';
import {Chtml} from '../mjs/util/Chtml.js';
import {Svg} from '../mjs/util/Svg.js';
import {Sre} from '../mjs/util/Sre.js';

//
// Load puppeteer support
//
import {Puppeteer} from './Puppeteer.js';

//
// Get the command-line arguments.
//
const args = await Util.args(
  '"math or filename" > file',
  [Typeset, Tex, Mml.input, Am, Chtml, Svg, Mml.output, Sre, Puppeteer]
);

Puppeteer.typeset(args)
  .then((output) => console.log(output))
  .catch(Puppeteer.error);
