#! node

/*************************************************************************
 *
 *  cjs/simple/mml2svg
 *
 *  Uses MathJax v4 to convert a MathML string to an SVG string.
 *
 * ----------------------------------------------------------------------
 *
 *  Copyright (c) 2019-2025 The MathJax Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

//
// Load MathJax.
//
const MathJax = require('@mathjax/src/source');

//
// Load the needed utilities.
//
const {Util} = require('../util/Util.js');
const {Mml} = require('../util/Mml.js');
const {Svg} = require('../util/Svg.js');
const {Sre} = require('../util/Sre.js');

//
// Allow the use of "await" in the main code
//
(async () => {

  //
  // Get the command-line arguments.
  //
  const args = Util.args('"math" > file.svg', [Mml.input, Svg, Sre]);

  //
  // Load and initialize MathJax.
  //
  await MathJax.init({
    loader:  Util.config.loader(['mml-svg'], args),
    options: Util.config.options(args),
    startup: Util.config.startup(args),
    mml:     Mml.input.config(args),
    svg:     Svg.config(args),
    'adaptors/liteDOM': Util.config.adaptor(args),
  });

  //
  // Typeset the math and print the result.
  //
  console.log(await Util.typeset(args, Svg));

  //
  // Tell MathJax we are done.
  //
  MathJax.done();

})();
