#! node

/*************************************************************************
 *
 *  cjs/simple/typeset
 *
 *  Uses MathJax v4 to convert any of its formats to any of its output types.
 *
 * ----------------------------------------------------------------------
 *
 *  Copyright (c) 2025 The MathJax Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

//
// Load MathJax.
//
const MathJax = require('@mathjax/src/source');

//
// Load the needed utilities.
//
const {Typeset} = require('../util/Typeset.js');
const {Util} = require('../util/Util.js');
const {Tex} = require('../util/Tex.js');
const {Mml} = require('../util/Mml.js');
const {Am} = require('../util/Am.js');
const {Chtml} = require('../util/Chtml.js');
const {Svg} = require('../util/Svg.js');
const {Sre} = require('../util/Sre.js');

//
// Allow the use of "await" in the main code
//
(async () => {

  //
  // Get the command-line arguments.
  //
  const args = Util.args(
    '"math or filename" > file',
    [Typeset, Tex, Mml.input, Am, Chtml, Svg, Mml.output, Sre]
  );

  //
  // Initialize MathJax with the provided arguments.
  //
  await MathJax.init(Typeset.config(args));

  //
  // Produce the output for the requested format.
  //
  console.log(await Util.typeset(args, Typeset));

  //
  // Tell MathJax we are done.
  //
  MathJax.done();

})();

