#! node

/*************************************************************************
 *
 *  mjs/direct/am2svg
 *
 *  Uses MathJax v4 to convert a AsciiMath string to an SVG string.
 *
 * ----------------------------------------------------------------------
 *
 *  Copyright (c) 2018-2025 The MathJax Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

//
// Load the packages needed for MathJax.
//
import {AsciiMath} from '@mathjax/src/js/input/asciimath.js';
import {SVG} from '@mathjax/src/js/output/svg.js';

//
// Load the needed utilities.
//
import {Direct} from '../util/Direct.js';
import {Util} from '../util/Util.js';
import {Am} from '../util/Am.js';
import {Svg} from '../util/Svg.js';
import {Sre} from '../util/Sre.js';
Am.AsciiMath = AsciiMath;

//
// Get the command-line arguments.
//
const args = await Util.args('"math" > file.svg', [Am, Svg, Sre, Direct]);

//
// Create the input and output jax.
//
const am = new AsciiMath(Am.config(args, AsciiMath));
const svg = new SVG(Svg.config(args));

//
// Create the MathDocument with the input and output jax.
//
const document = Direct.document(am, svg, args);
  
//
// Typeset the math and print the result.
//
console.log(await Util.typeset(args, Svg, document));

//
// Tell MathJax we are done.
//
document.done();
