#! node

/*************************************************************************
 *
 *  mjs/simple/mml2mml
 *
 *  Uses MathJax v4 to normalize a MathML string.
 *
 * ----------------------------------------------------------------------
 *
 *  Copyright (c) 2025 The MathJax Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

//
// Load MathJax.
//
import MathJax from '@mathjax/src';

//
// Load the needed utilities.
//
import {Util} from '../util/Util.js';
import {Mml} from '../util/Mml.js';

//
// Get the command-line arguments.
//
const args = await Util.args('"math"', [Mml.input, Mml.output], false);

//
// Load and initialize MathJax.
//
await MathJax.init({
  loader:  Util.config.loader(['input/mml'], args),
  options: Util.config.options(args),
  startup: Util.config.startup(args),
  mml:     Mml.input.config(args),
  'adaptors/liteDOM': Util.config.adaptor(args),
});

//
// Convert and print the math.
//
console.log(await Util.typeset(args, Mml));
