#! node

/*************************************************************************
 *
 *  mjs/mixed/typeset
 *
 *  Uses MathJax v4 to convert any of its formats to any of its output types.
 *
 * ----------------------------------------------------------------------
 *
 *  Copyright (c) 2025 The MathJax Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

//
// Load the needed utilities.
//
import {Mixed} from '../util/Mixed.js';
import {Typeset} from '../util/Typeset.js';
import {Util} from '../util/Util.js';
import {Tex} from '../util/Tex.js';
import {Mml} from '../util/Mml.js';
import {Am} from '../util/Am.js';
import {Chtml} from '../util/Chtml.js';
import {Svg} from '../util/Svg.js';
import {Sre} from '../util/Sre.js';

//
// Get the command-line arguments.
//
const args = await Util.args(
  '"math or filename" > file',
  [Typeset, Tex, Mml.input, Am, Chtml, Svg, Mml.output, Sre, Mixed]
);

//
// Create input and output jax.
//
const input = await Typeset.create.input(args);
const output = await Typeset.create.output(args);

//
// Create the MathDocument with the input and output jax.
//
const document = Mixed.document(input, output, args);

//
// Produce the output for the requested format.
//
console.log(await Util.typeset(args, Typeset, document));

//
// Tell MathJax we are done.
//
document.done();
