#! /usr/bin/env -S node -r esm

/*************************************************************************
 *
 *  preload/mml2svg-page
 *
 *  Uses MathJax v3 to convert all MathML in an HTML document.
 *
 * ----------------------------------------------------------------------
 *
 *  Copyright (c) 2019 The MathJax Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

//
//  Get the command-line arguments
//
var argv = require('yargs')
    .demand(0).strict()
    .usage('$0 [options] file.html > converted.html')
    .options({
        em: {
            default: 16,
            describe: 'em-size in pixels'
        },
        ex: {
            default: 8,
            describe: 'ex-size in pixels'
        },
        fontCache: {
            default: 'global',
            describe: 'cache type: local, global, none'
        },
    })
    .argv;

//
//  Read the HTML file
//
const htmlfile = require('fs').readFileSync(argv._[0], 'utf8');

//
//  Configure MathJax
//
MathJax = {
    svg: {
        fontCache: argv.fontCache,
        exFactor: argv.ex / argv.em
    },
    'adaptors/liteDOM': {
        fontSize: argv.em
    },
    startup: {
        document: htmlfile,
        typeset: false
    },
    loader: {
        require: require
    }
};

//
//  Load the needed components
//
require('mathjax-full/components/src/mml-svg/mml-svg.js');
require('mathjax-full/components/src/adaptors/liteDOM/liteDOM.js');

//
//  Let MathJax know these are loaded
//
MathJax.loader.preLoad(
    'mml-svg',
    'adaptors/liteDOM'
);

//
//  Create the MathJax methods for the input and output that is loaded
//
MathJax.config.startup.ready();

//
//  Typeset the document
//
MathJax.typeset();
const adaptor = MathJax.startup.adaptor;
const html = MathJax.startup.document;

//
//  If no math was found on the page, remove the stylesheet and font cache (if any)
//
if (html.math.toArray().length === 0) {
  adaptor.remove(html.outputJax.svgStyles);
  const cache = adaptor.elementById(adaptor.body(html.document), 'MJX-SVG-global-cache');
  if (cache) adaptor.remove(cache);
}

//
//  Output the resulting HTML
//
console.log(adaptor.doctype(html.document));
console.log(adaptor.outerHTML(adaptor.root(html.document)));
